server:
  port: 8189
  servlet:
    context-path: /admin
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_eshop_db?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: geek
    password: geek
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

#  spring.socket.server.port=8189
#  server.servlet.context-path=/admin
#
#  spring.datasource.url=jdbc:mysql://localhost:3306/spring_eshop_db?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC
#  spring.datasource.username=geek
#  spring.datasource.password=geek
#  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#  spring.jpa.show-sql=true
#  spring.jpa.properties.hibernate.format_sql=true
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#  spring.jpa.hibernate.ddl-auto=validate
#
#  spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
#  spring.liquibase.enabled=false
#
#  spring.mvc.hiddenmethod.filter.enabled=true